### ISSUE TITLE
Visa Checkout not working in iOS SDK v5

### ISSUE THREAD

**Issue by cminero10** [braintree/braintree-ios-visa-checkout#15]
**Integration Details (please complete the following information):**
 - Braintree SDK Version: 5.4.4
 - Environment: Sandbox
 - iOS Version: 13.0+
 - Xcode Version: Xcode 12.5
 - Device: Xcode simulator device
 - Integration type & version: Swift Package Manager 5.4

**Describe the bug**
I am not able to use VisaCheckout anymore in my app, I followed the SPM instructions in the Braintree iOS v5 Migration Guide to add the required libraries too my project but I could not find any reference to VisaCheckout framework, so I got errors in each part where I had implemented VC across my app.

**To Reproduce**
Migrate from v4 to v5

**Expected behavior**
Import VisaCheckout in my project and implement the VCO button.

**Screenshots**

![image](https://user-images.githubusercontent.com/28816567/140377780-79f2a0a7-d0a3-4c7d-83c8-0c2ef0a21b3a.png)

<img width="214" alt="PastedGraphic-4" src="https://user-images.githubusercontent.com/28816567/140377872-5a57f15b-5c05-4be8-ba29-6c62b538bc5d.png">

**Comment by cminero10** [comment]
https://github.com/braintree/braintree_ios/issues/754

**Comment by scannillo** [comment]
So this is 2 separate issues:

1) Visa Checkout SDK doesn't offer SPM support right now
2) Visa Checkout SDK hasn't been updated for use with `braintree_ios` v5

I will bring these requests up with our team and keep you posted on timelines when we have them! Thank you for raising this issue.

**Comment by scannillo** [comment]
👋  Hi, this work is in progress here https://github.com/braintree/braintree-ios-visa-checkout/pull/16 if you would like to track it!

**Comment by cminero10** [comment]
Thanks for the update, I really appreciate it

**Comment by scannillo** [comment]
👋  Hi @cminero10  - just wanted to update you that we're almost done wrapping up these updates. You can check out the `next-major-version` branch (https://github.com/braintree/braintree-ios-visa-checkout/tree/next-major-version) where we add SPM support as well as update to use `braintree_ios` v5.

Feel free to pull down that branch in the meantime, while we wrap up final testing before making an official release!

**Comment by scannillo** [comment]
These changes have been released! https://github.com/braintree/braintree-ios-visa-checkout/releases/tag/6.0.0

**Comment by cminero10** [comment]
Hi, thank you for this, I have tried to integrate into my project using SPM but I got the following:

![image](https://user-images.githubusercontent.com/28816567/145122409-5f97baea-b28a-4bdb-9bb2-8046d001e807.png)

**Comment by scannillo** [comment]
👋  Hi @cminero10 - the v6 version of this SDK requires Xcode 13 (which includes Swift tools v5.5.0). We call this out in the README. If you update to Xcode 13, that should resolve the issue.

**Comment by cminero10** [comment]
Thank you, I will do, I really appreciate your quick turnaround :)

**Comment by cminero10** [comment]
Hi, I have updated Xcode to 13 version and was able to import through SPM, but now I got the following errors:

1.
![image](https://user-images.githubusercontent.com/28816567/145656597-64114797-6ad6-454e-80af-935068ed9108.png)

2.
![image](https://user-images.githubusercontent.com/28816567/145656627-debdbaa5-238d-40ef-9665-e7db3ced1081.png)

**Comment by scannillo** [comment]
I would remove the `braintree-ios-visa-checkout` package entirely, then re-add into your application. Also, clean the project and delete derived data.

**Comment by cminero10** [comment]
Hi, I have followed the steps above but the issue persists, I removed the package, re-add it, cleaned the project and delete derived data, all these twice. :(

**Comment by scannillo** [comment]
Are you using CocoaPods elsewhere in your project?

We aren't able to replicate this issue in a standalone application that pulls in BraintreeVisaCheckout through SPM. 

I recommend you create a blank application, from scratch via Xcode, pull in BraintreeVisaCheckout via SPM, and see if you can replicate that way - my guess is no, since we also can't.

**Comment by cminero10** [comment]
Yes, I use CocoaPods for other libraries and use SPM for all Braintree related.

I will follow your instructions creating a blank project. Thanks

**Comment by cminero10** [comment]
Hello, I have created a new project using only SPM and it worked.

Now, since in my real project I need to use other pods via CocoaPods I can't rely only in SPM. I have commented the following lines in each part they appear and I was able to run my project.

![image](https://user-images.githubusercontent.com/28816567/146125872-c4f64f7f-48e3-4912-9285-8f540acaeee6.png)

But I still see the old payment sheet of Visa Checkout that request Username and Password and not the new way that only request Username and send a One time password:

![simulator_screenshot_8F5658C7-A874-40CA-8F94-9B128123A07E](https://user-images.githubusercontent.com/28816567/146125984-23f54660-f405-45d6-8138-705b4c23a944.png)

How can I display the VCO payment sheet with the new experience like this:

https://user-images.githubusercontent.com/28816567/146127023-afed604b-cba4-45bf-8359-3ed3101b7369.mp4

https://user-images.githubusercontent.com/28816567/146127029-49235c23-ea27-43db-94b4-8a00a5d903cb.mp4

reference: Visa Developer demo app.

![image](https://user-images.githubusercontent.com/28816567/146127696-bc7c3d69-22fc-4875-91e4-f5f08e9c0fd4.png)


Thank you!

**Comment by cminero10** [comment]
Hi 👋🏻 , I would like to know if you have planned to work on this soon or have a tentative date to be released? 🙂

Thank you in advance.

**Comment by cminero10** [comment]
Hi 👋🏻 , I would like to know if you have planned to work on this soon or have a tentative date to be released? 🙂

Thank you in advance.
